
REPLACE INTO {table_prefix}soconfig VALUES

(null,"{store_id}","soconfig_custom_store","{\"cssinput_status\":\"0\",\"cssinput_content\":\"\",\"cssfile_status\":\"0\",\"cssfile_url\":[\"catalog\\/view\\/theme\\/so-revo\\/css\\/custom.css\"],\"jsinput_status\":\"0\",\"jsinput_content\":\"\"}","1"),
(null,"{store_id}","soconfig_social_store","{\"social_sidebar\":\"0\",\"social_fb_status\":\"1\",\"facebook\":\"magentech\",\"social_twitter_status\":\"1\",\"twitter\":\"smartaddons\",\"social_custom_status\":\"1\",\"video_code\":{\"2\":\"&lt;p&gt;Custom block Html&lt;\\/p&gt;\",\"1\":\"&lt;p&gt;Custom block Html&lt;\\/p&gt;\"}}","1"),
(null,"{store_id}","soconfig_advanced_store","{\"name_color\":\"bright_orange\",\"theme_color\":\"#Ff782e\",\"scsscompile\":\"0\",\"scssformat\":\"Nested\",\"compileMutiColor\":\"0\",\"cssminify\":\"0\",\"cssExclude\":[{\"namecss\":\"extension\\/so_theme\\/catalog\\/view\\/javascript\\/font-awesome\\/css\\/font-awesome.min.css\"}],\"jsminify\":\"0\",\"jsExclude\":[{\"namecss\":\"extension\\/so_theme\\/catalog\\/view\\/javascript\\/jquery\\/datetimepicker\\/moment-with-locales.min.js\"}]}","1"),
(null,"{store_id}","soconfig_layout_store","{\"layout_other_boxed\":\"0\",\"layoutstyle\":\"full\",\"theme_bgcolor\":\"#7a167a\",\"pattern\":\"6\",\"contentbg\":\"\",\"content_bg_mode\":\"repeat\",\"content_attachment\":\"scroll\"}","1"),
(null,"{store_id}","soconfig_pages_store","{\"catalog_col_position\":\"outside\",\"catalog_col_type\":\"default\",\"product_catalog_refine\":\"0\",\"catalog_refine_number\":\"4\",\"lstimg_cate_status\":\"0\",\"product_catalog_mode\":\"grid-4\",\"discount_status\":\"1\",\"countdown_status\":\"1\",\"rating_status\":\"0\",\"card_gallery\":\"2\",\"placeholder_status\":\"0\",\"placeholder_img\":\"catalog\\/logo.png\",\"desktop_addcart_position\":\"left\",\"quick_status\":\"1\",\"desktop_addcart_status\":\"1\",\"desktop_wishlist_status\":\"1\",\"desktop_Compare_status\":\"1\",\"radio_style\":\"1\",\"thumbnails_position\":\"bottom\",\"product_enablezoom\":\"1\",\"product_order\":\"1\",\"product_enableshowmore\":\"0\",\"tabs_position\":\"2\",\"product_enablesizechart\":\"1\",\"product_enableshipping\":\"0\",\"product_contentshipping\":{\"2\":\"&lt;p&gt;Custom block Html&lt;\\/p&gt;\",\"1\":\"&lt;p&gt;Custom block Html&lt;\\/p&gt;\"},\"product_page_button\":\"1\",\"product_socialshare\":{\"2\":\"&lt;p&gt;Share This&lt;\\/p&gt;\",\"1\":\"&lt;p&gt;Share This&lt;\\/p&gt;\"},\"related_status\":\"1\",\"product_related_column_lg\":\"4\",\"product_related_column_md\":\"3\",\"product_related_column_sm\":\"2\",\"product_related_column_xs\":\"1\",\"comingsoon_imglogo\":\"catalog\\/logo.png\",\"comingsoon_title\":{\"2\":\"Coming Soon Title\",\"1\":\"Coming Soon Title\"},\"comingsoon_date\":\"2018-05-26\",\"comingsoon_content\":{\"2\":\"&lt;p&gt;Coming soon content&lt;\\/p&gt;\",\"1\":\"&lt;p&gt;Coming soon content&lt;\\/p&gt;\"}}","1"),
(null,"{store_id}","soconfig_fonts_store","{\"body_status\":\"google\",\"normal_body\":\"Arial, Helvetica, sans-serif\",\"url_body\":\"https:\\/\\/fonts.googleapis.com\\/css?family=Roboto:300,400,500,700\",\"family_body\":\"\'Roboto\', sans-serif\",\"selector_body\":\"body, #wrapper\",\"menu_status\":\"standard\",\"normal_menu\":\"inherit\",\"url_menu\":\"\",\"family_menu\":\"\",\"selector_menu\":\"\",\"heading_status\":\"standard\",\"normal_heading\":\"inherit\",\"url_heading\":\"\",\"family_heading\":\"\",\"selector_heading\":\"\"}","1"),
(null,"{store_id}","soconfig_general_store","{\"typelayout\":\"6\",\"themecolor\":\"bright_orange\",\"toppanel_status\":\"0\",\"toppanel_type\":\"1\",\"sticky_buynow_status\":\"1\",\"phone_status\":\"0\",\"contact_number\":{\"2\":\"(84+) 1234455667\",\"1\":\"(84+) 1234455669\"},\"welcome_message_status\":\"1\",\"welcome_message\":{\"2\":\"Gift every single day on Weekends - New Coupon code: Happy2017\",\"1\":\"Gift every single day on Weekends - New Coupon code: Happy2017\"},\"checkout_status\":\"0\",\"lang_status\":\"1\",\"preloader\":\"1\",\"preloader_animation\":\"line\",\"imgpayment_status\":\"1\",\"imgpayment\":\"catalog\\/demo\\/payment\\/payment-6.png\",\"copyright\":\"eMarket \\u00a9 {year} Demo Store. All Rights Reserved. Designed by &lt;a href=&quot;http:\\/\\/www.Smartaddons.Com\\/&quot; target=&quot;_blank&quot;&gt;Smartaddons.Com&lt;\\/a&gt;\",\"typeheader\":\"6\",\"typefooter\":\"6\",\"type_banner\":\"4\",\"mapaddress\":\"685 Market Street San Francisco, CA 94105\",\"mapgeocode\":\"40.705423,-74.008616\",\"mapkeys\":\"AIzaSyCdLmykXAklykOYyXdILXpZvQGPmc58LIk\",\"mapzoom\":\"16\",\"img_sizechart\":\"catalog\\/demo\\/size-chart.jpg\"}","1");
